# Generated by Django 4.2.2 on 2023-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='baslik')),
                ('content', models.TextField(verbose_name='icerik')),
                ('publishingDate', models.DateTimeField(auto_now_add=True, verbose_name='yayinlanma tarihi')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-publishingDate'],
            },
        ),
    ]
