# Generated by Django 4.2.2 on 2023-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='icerik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishingDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yayinlanma tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='baslik'),
        ),
    ]
